// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: client/api/v1/saveClientFS.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientFS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InitDir     string            `protobuf:"bytes,1,opt,name=initDir,proto3" json:"initDir,omitempty"`
	Directories []string          `protobuf:"bytes,2,rep,name=directories,proto3" json:"directories,omitempty"`
	AllFiles    map[string]string `protobuf:"bytes,3,rep,name=allFiles,proto3" json:"allFiles,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Changes     map[string]string `protobuf:"bytes,4,rep,name=changes,proto3" json:"changes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ClientFS) Reset() {
	*x = ClientFS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_api_v1_saveClientFS_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientFS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientFS) ProtoMessage() {}

func (x *ClientFS) ProtoReflect() protoreflect.Message {
	mi := &file_client_api_v1_saveClientFS_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientFS.ProtoReflect.Descriptor instead.
func (*ClientFS) Descriptor() ([]byte, []int) {
	return file_client_api_v1_saveClientFS_proto_rawDescGZIP(), []int{0}
}

func (x *ClientFS) GetInitDir() string {
	if x != nil {
		return x.InitDir
	}
	return ""
}

func (x *ClientFS) GetDirectories() []string {
	if x != nil {
		return x.Directories
	}
	return nil
}

func (x *ClientFS) GetAllFiles() map[string]string {
	if x != nil {
		return x.AllFiles
	}
	return nil
}

func (x *ClientFS) GetChanges() map[string]string {
	if x != nil {
		return x.Changes
	}
	return nil
}

type SaveChanges struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Seq         uint32            `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`                                                                                                        // 변경파일을 저장할 디렉터리명에 사용할 시퀀스 정보
	Msg         string            `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`                                                                                                         // 변경 메세지
	ChangeOrder map[string]string `protobuf:"bytes,2,rep,name=changeOrder,proto3" json:"changeOrder,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // 변경된 파일 정보
}

func (x *SaveChanges) Reset() {
	*x = SaveChanges{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_api_v1_saveClientFS_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SaveChanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveChanges) ProtoMessage() {}

func (x *SaveChanges) ProtoReflect() protoreflect.Message {
	mi := &file_client_api_v1_saveClientFS_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveChanges.ProtoReflect.Descriptor instead.
func (*SaveChanges) Descriptor() ([]byte, []int) {
	return file_client_api_v1_saveClientFS_proto_rawDescGZIP(), []int{1}
}

func (x *SaveChanges) GetSeq() uint32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SaveChanges) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *SaveChanges) GetChangeOrder() map[string]string {
	if x != nil {
		return x.ChangeOrder
	}
	return nil
}

type ChangeHistory struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	History []*SaveChanges `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"` // 전체 변경 내역을 저장
}

func (x *ChangeHistory) Reset() {
	*x = ChangeHistory{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_api_v1_saveClientFS_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeHistory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeHistory) ProtoMessage() {}

func (x *ChangeHistory) ProtoReflect() protoreflect.Message {
	mi := &file_client_api_v1_saveClientFS_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeHistory.ProtoReflect.Descriptor instead.
func (*ChangeHistory) Descriptor() ([]byte, []int) {
	return file_client_api_v1_saveClientFS_proto_rawDescGZIP(), []int{2}
}

func (x *ChangeHistory) GetHistory() []*SaveChanges {
	if x != nil {
		return x.History
	}
	return nil
}

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Pw              string `protobuf:"bytes,2,opt,name=pw,proto3" json:"pw,omitempty"`
	GarageName      string `protobuf:"bytes,3,opt,name=garageName,proto3" json:"garageName,omitempty"`
	ChildProcessPid int32  `protobuf:"varint,4,opt,name=childProcessPid,proto3" json:"childProcessPid,omitempty"`
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_api_v1_saveClientFS_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_api_v1_saveClientFS_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_client_api_v1_saveClientFS_proto_rawDescGZIP(), []int{3}
}

func (x *UserInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserInfo) GetPw() string {
	if x != nil {
		return x.Pw
	}
	return ""
}

func (x *UserInfo) GetGarageName() string {
	if x != nil {
		return x.GarageName
	}
	return ""
}

func (x *UserInfo) GetChildProcessPid() int32 {
	if x != nil {
		return x.ChildProcessPid
	}
	return 0
}

var File_client_api_v1_saveClientFS_proto protoreflect.FileDescriptor

var file_client_api_v1_saveClientFS_proto_rawDesc = []byte{
	0x0a, 0x20, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f,
	0x73, 0x61, 0x76, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46, 0x53, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x66, 0x73, 0x2e, 0x76, 0x31, 0x22,
	0xbe, 0x02, 0x0a, 0x08, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46, 0x53, 0x12, 0x18, 0x0a, 0x07,
	0x69, 0x6e, 0x69, 0x74, 0x44, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69,
	0x6e, 0x69, 0x74, 0x44, 0x69, 0x72, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x08, 0x61, 0x6c, 0x6c, 0x46,
	0x69, 0x6c, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x66, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46,
	0x53, 0x2e, 0x41, 0x6c, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x08, 0x61, 0x6c, 0x6c, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x07, 0x63, 0x68, 0x61,
	0x6e, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x66, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46,
	0x53, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x1a, 0x3b, 0x0a, 0x0d, 0x41, 0x6c, 0x6c, 0x46, 0x69,
	0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x1a, 0x3a, 0x0a, 0x0c, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0xbe, 0x01, 0x0a, 0x0b, 0x53, 0x61, 0x76, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x73,
	0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x12, 0x4b, 0x0a, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x66, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x43, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x1a, 0x3e, 0x0a, 0x10, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x43, 0x0a, 0x0d, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x48, 0x69, 0x73, 0x74, 0x6f,
	0x72, 0x79, 0x12, 0x32, 0x0a, 0x07, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x66, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x61, 0x76, 0x65, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x52, 0x07, 0x68,
	0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x22, 0x74, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x70, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x70, 0x77, 0x12, 0x1e, 0x0a, 0x0a, 0x67, 0x61, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x61, 0x72, 0x61, 0x67, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x50, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0f, 0x63, 0x68, 0x69,
	0x6c, 0x64, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x50, 0x69, 0x64, 0x42, 0x26, 0x5a, 0x24,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x6f, 0x64, 0x61, 0x6d,
	0x69, 0x2d, 0x68, 0x75, 0x62, 0x2f, 0x77, 0x61, 0x74, 0x63, 0x68, 0x66, 0x73, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_api_v1_saveClientFS_proto_rawDescOnce sync.Once
	file_client_api_v1_saveClientFS_proto_rawDescData = file_client_api_v1_saveClientFS_proto_rawDesc
)

func file_client_api_v1_saveClientFS_proto_rawDescGZIP() []byte {
	file_client_api_v1_saveClientFS_proto_rawDescOnce.Do(func() {
		file_client_api_v1_saveClientFS_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_api_v1_saveClientFS_proto_rawDescData)
	})
	return file_client_api_v1_saveClientFS_proto_rawDescData
}

var file_client_api_v1_saveClientFS_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_client_api_v1_saveClientFS_proto_goTypes = []interface{}{
	(*ClientFS)(nil),      // 0: clientfs.v1.ClientFS
	(*SaveChanges)(nil),   // 1: clientfs.v1.SaveChanges
	(*ChangeHistory)(nil), // 2: clientfs.v1.ChangeHistory
	(*UserInfo)(nil),      // 3: clientfs.v1.UserInfo
	nil,                   // 4: clientfs.v1.ClientFS.AllFilesEntry
	nil,                   // 5: clientfs.v1.ClientFS.ChangesEntry
	nil,                   // 6: clientfs.v1.SaveChanges.ChangeOrderEntry
}
var file_client_api_v1_saveClientFS_proto_depIdxs = []int32{
	4, // 0: clientfs.v1.ClientFS.allFiles:type_name -> clientfs.v1.ClientFS.AllFilesEntry
	5, // 1: clientfs.v1.ClientFS.changes:type_name -> clientfs.v1.ClientFS.ChangesEntry
	6, // 2: clientfs.v1.SaveChanges.changeOrder:type_name -> clientfs.v1.SaveChanges.ChangeOrderEntry
	1, // 3: clientfs.v1.ChangeHistory.history:type_name -> clientfs.v1.SaveChanges
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_client_api_v1_saveClientFS_proto_init() }
func file_client_api_v1_saveClientFS_proto_init() {
	if File_client_api_v1_saveClientFS_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_client_api_v1_saveClientFS_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientFS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_api_v1_saveClientFS_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SaveChanges); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_api_v1_saveClientFS_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeHistory); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_api_v1_saveClientFS_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_api_v1_saveClientFS_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_client_api_v1_saveClientFS_proto_goTypes,
		DependencyIndexes: file_client_api_v1_saveClientFS_proto_depIdxs,
		MessageInfos:      file_client_api_v1_saveClientFS_proto_msgTypes,
	}.Build()
	File_client_api_v1_saveClientFS_proto = out.File
	file_client_api_v1_saveClientFS_proto_rawDesc = nil
	file_client_api_v1_saveClientFS_proto_goTypes = nil
	file_client_api_v1_saveClientFS_proto_depIdxs = nil
}
